### PR TITLE
Add provisioned Grafana dashboard to scalardb-graphql Helm chart

### PR DESCRIPTION
**Pull request by ymorimo**
This PR adds a provisioned Grafana dashboard JSON configuration file for the GraphQL Prometheus metrics.

Please note that this PR is built on top of #110.

---

### Start Cassandra and load the emoney schema

```console
docker run -d --rm --name cassandra-scalardb --network minikube -p 9042:9042 cassandra:3.11
java -jar scalardb-schema-loader-3.5.0.jar --config database.properties --coordinator -f emoney-schema.json
```

### Deploy `kube-prometheus-stack` to the `monitoring` namespace

Deploy `kube-prometheus-stack` by following the step 2 and 3 of the Getting Started with Helm Charts:
https://github.com/scalar-labs/helm-charts/blob/main/docs/getting-started-monitoring.md#step-2-prepare-a-custom-values-file

### Load the latest scalardb-graphql build to minikube

```console
minikube image load ghcr.io/scalar-labs/scalardb-graphql:4.0.0-SNAPSHOT
minikube image tag ghcr.io/scalar-labs/scalardb-graphql:4.0.0-SNAPSHOT local/test/scalardb-graphql:4.0.0-SNAPSHOT
```

### Create a custom values file

```yaml
scalarDbGraphQlConfiguration:
  contactPoints: cassandra-scalardb
  contactPort: 9042
  username: cassandra
  password: cassandra
  storage: cassandra
  logLevel: INFO
  path: /graphql
  namespaces: emoney
  graphiql: "true"

image:
  repository: local/test/scalardb-graphql
  tag: 4.0.0-SNAPSHOT

service:
  type: LoadBalancer

serviceMonitor:
  enabled: true

prometheusRule:
  enabled: true

grafanaDashboard:
  enabled: true

ingress:
  enabled: true
  className: nginx
```

### Install scalardb-graphql chart

```console
helm install scalardb-graphql ./charts/scalardb-graphql -f custom-values.yaml
```

### Open Grafana

Run `minikube tunnel` and open http://localhost:3000/.

To cause a GraphQL error, for example, send an invalid GraphQL document like the following:

```console
curl -v http://localhost:8080/graphql -H 'Content-Type: application/graphql' --data '{}'
```

To cause an HTTP error, for example, send a request with an invalid `Content-Type`

```console
curl -v http://localhost:8080/graphql -H 'Content-Type: text/plain' -X POST
```

### CODE REVIEW

**Comment by ymorimo** [comment]
> I think the above requests are the **health check requests** related to the following configuration in the deployment resource.
> 
> I think this health check runs actual graphql requests. Is my understanding correct?

Yes, the health check requests run actual GraphQL queries. `__typename` is a meta field to request the name of the object type, so when a document `{__typename}` is sent, the server answers `Query` to it.

```
curl localhost:8080/graphql -H 'Content-Type: application/graphql' --data '{__typename}'
{"data":{"__typename":"Query"}}
```

Running this query can check if the container is live and ready

**Comment by ymorimo** [comment]
@kota2and3kan 

> I think the above requests are the **health check requests** related to the following configuration in the deployment resource.
> 
> I think this health check runs actual graphql requests. Is my understanding correct?

Yes, the health check requests run actual GraphQL queries. `__typename` is a meta field to request the name of the object type, so when a document `{__typename}` is sent, the server answers `Query` to it.

```
$ curl localhost:8080/graphql -H 'Content-Type: application/graphql' --data '{__typename}'
{"data":{"__typename":"Query"}}
```

Actually, I'm not fully sure this is the best way, but I think this query is the simplest and makes sure the server accepts actual GraphQL queries.

**Comment by kota2and3kan** [comment]
@ymorimo 
> Yes, the health check requests run actual GraphQL queries. `__typename` is a meta field to request the name of the object type, so when a document `{__typename}` is sent, the server answers `Query` to it.

I understood! Thank you!

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@ymorimo Can you please resolve the conflict?

**Comment by ymorimo** [comment]
> @ymorimo Can you please resolve the conflict?

@brfrn169 Thank you for the review. I've just resolved the conflicts.

**Pull request merged**
