### PR TITLE
Update Envoy Helm Chart to 2.1.0 (use scalar-envoy 1.3.0)

### PR DESCRIPTION
**Pull request by supl**
This PR updates Envoy Helm Chart to 2.1.0.

It's the latest update so I create this PR to merge the change to the main branch.

(Envoy Helm Chart 2.1.0 is already released by prepare-release-v2.1.0 branch pushed)

### CODE REVIEW

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by feeblefakie** [comment]
@supl Please fix the conflicts! 🙇

**Comment by supl** [comment]
@feeblefakie 
Thank you!
I resolved the conflicts and the CI passed so I merged this PR.

**Pull request merged**
