### PR TITLE
Check for bump up scalardl to v4.1.1

### PR DESCRIPTION
**Pull request by kota2and3kan**
I changed version of scalardl for release new version.
```
$ git checkout -b check-release-v4.1.1 refs/tags/scalardl-4.1.0
```

Could you please confirm the changes?

If there is no problem, I will create prepare-release-v4.1.1 branch in the same way, for release new version. Also, I will release each minor version of scalardl, and release scalardl-audit in the same way.

### CODE REVIEW

**Review by miseyu — APPROVED** [review]

**Comment by kota2and3kan** [comment]
Thank you for confirmation!
I will create each `prepare-release-*` branch in the same way.

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by feeblefakie** [comment]
@miseyu In this case, there is no difference, but we should have created a branch from main?

**Comment by miseyu** [comment]
@feeblefakie 
You're right.:bow:

**Comment by kota2and3kan** [comment]
I'm sorry for the mistake.🙇
I will be careful about branch that I create from.

**Pull request merged**
