### PR TITLE
[scalar-manager] Add probes for health checking

### PR DESCRIPTION
**Pull request by kota2and3kan**
This PR adds `Probes` in the Scalar Manager chart.

In the current chart, there is no health checking in Scalar Manager deployment. I think this is not good for the production environment. So, I added `Probes` for the health checking of Scalar Manager.

Note: Scalar Manager doesn't have a health check endpoint like `/health`. So, I use `/` for health checking. We are planning to add `/health` endpoint in the Scalar Manager side in the future. After we implement `/health` endpoint in Scalar Manager, I will update this chart again to use that endpoint.

Please take a look!

### CODE REVIEW

**Comment by supl** [comment]
> Note: Scalar Manager doesn't have a health check endpoint like /health. So, I use / for health checking. We are planning to add /health endpoint in the Scalar Manager side in the future. After we implement /health endpoint in Scalar Manager, I will update this chart again to use that endpoint.

I created a PR for adding the `/health` endpoint.
https://github.com/scalar-labs/scalar-manager/pull/47

For your reference.

Thank you for the reminder 🙇

**Review by supl — APPROVED** [review]
LGTM.
Thank you!

**Comment by kota2and3kan** [comment]
@supl 
> I created a PR for adding the `/health` endpoint.
> https://github.com/scalar-labs/scalar-manager/pull/47

Thank you for the quick implementation!
I think we can use the `/health` endpoint in this helm chart after https://github.com/scalar-labs/scalar-manager/pull/47 will be merged.
So, I will wait for merging it and update this PR to use the `/health` endpoint.

**Comment by supl** [comment]
> @supl
> 
> > I created a PR for adding the `/health` endpoint.
> > [scalar-labs/scalar-manager#47](https://github.com/scalar-labs/scalar-manager/pull/47)
> 
> Thank you for the quick implementation! I think we can use the `/health` endpoint in this helm chart after [scalar-labs/scalar-manager#47](https://github.com/scalar-labs/scalar-manager/pull/47) will be merged. So, I will wait for merging it and update this PR to use the `/health` endpoint.

Thank you.

I just merged the PR and the SNAPSHOT image is pushed (by CI) too.
https://github.com/orgs/scalar-labs/packages/container/package/scalar-manager

For your reference 🙇

**Comment by kota2and3kan** [comment]
According to the discussion and investigation result in the following comment, I removed `readinessProbe`.
https://github.com/scalar-labs/helm-charts/pull/220#discussion_r1197511801

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
