### PR TITLE
[scalardl-ledger] Support TLS for ServiceMonitor in ScalarDL Ledger chart

### PR DESCRIPTION
**Pull request by kota2and3kan**
## Description

This PR updates the `ServiceMonitor` resource to support the TLS connection from Prometheus to ScalarDL Ledger.

After this update, we can run the scrape requests from Prometheus with TLS.

Please take a look!

## Related issues and/or PRs

- This PR depends on the following PR.
  - https://github.com/scalar-labs/helm-charts/pull/264 
- You can see the document about this new feature in the following PR.
  - https://github.com/scalar-labs/docs-internal-orchestration/pull/25

## Changes made

- Add new custom value `ledger.tls.caRootCertSecretForServiceMonitor` to specify the secret resource name that includes root CA certificate of ScalarDL Ledger.
- Update `charts/scalardl/templates/ledger/servicemonitor.yaml` to enable TLS configurations when we set `ledger.tls.enabled=true`.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

Support TLS in the scrape requests from Prometheus in the ScalarDL Ledger chart.

### CODE REVIEW

**Review by supl — APPROVED** [review]
LGTM.
Thank you!

**Review by choplin — APPROVED** [review]
LGTM!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by jnmt — APPROVED** [review]
LGTM! Thank you!

**Review by superbrothers — APPROVED** [review]

**Pull request merged**
