### PR TITLE
Revise the document of scalar-admin-for-kubernetes

### PR DESCRIPTION
**Pull request by supl**
## Description

This PR revises the document of using scalar-admin-for-kubernetes Helm Chart. I guess we forgot to revise this part when we change the custom values template in https://github.com/scalar-labs/helm-charts/pull/246#discussion_r1419993371.

## Related issues and/or PRs

https://github.com/scalar-labs/helm-charts/pull/246#discussion_r1419993371

## Changes made

- revised `configure-custom-values-scalar-admin-for-kubernetes.md`

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [ ] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [ ] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes in other PRs have been merged and published.

### CODE REVIEW

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

**Comment by kota2and3kan** [comment]
@josh-wong  
This is a minor update. So, I will just merge it. Could you please apply it to the Scalar Doc Site after I merge it?

**Review by josh-wong — APPROVED** [review]
LGTM! Thank you!🙇‍♂️

**Comment by josh-wong** [comment]
@kota2and3kan 
> @josh-wong This is a minor update. So, I will just merge it. Could you please apply it to the Scalar Doc Site after I merge it?

Sorry for the delay! Just reviewed and approved🙇🏻‍♂️

**Comment by supl** [comment]
@kota2and3kan 

I will merge this PR!

**Pull request merged**
